name: Race
version: 1.6.4-0.0.2
main: com.plugin.test.Main
commands:
  race:
    description: Base command for the Race plugin
permissions:
    race.set:
        description: race command permissions
        default: false
    race.get:
        description: race command permissions
        default: false